server:
  port: 8083
  host: "127.0.0.1"

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "111111"
  dbname: "voice_clone_db"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local" 