data:
  output_dir: model/data/outputs
  temp_dir: model/data/temp
  upload_dir: model/data/uploads
model:
  # 通用配置
  device: cpu
  n_mels: 80
  sample_rate: 22050
  model_dir: model/data/checkpoints
  
  # 文本编码器配置
  vocab_size: 256
  text_embed_dim: 512
  encoder_hidden_dim: 1024
  encoder_layers: 4
  encoder_heads: 8
  encoder_dropout: 0.1
  
  # 说话人编码器配置
  audio_n_mels: 80
  speaker_hidden_dim: 256
  speaker_embedding_dim: 256
  speaker_encoder_layers: 3
  embedding_dim: 256
  hidden_dim: 512
  
  # 梅尔解码器配置
  decoder_dim: 512
  decoder_layers: 4
  decoder_heads: 8
  decoder_ff_dim: 2048
  decoder_dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.0001
  max_epochs: 1000
  warmup_steps: 4000
  save_interval: 10
  eval_interval: 5

paths:
  checkpoint_dir: model/data/checkpoints
  log_dir: model/data/logs
  data_dir: model/data
server:
  debug: false
  host: 0.0.0.0
  port: 7860
  upload_dir: model/data/uploads
test:
  audio: model/data/wavs/sample.wav
  output_dir: model/data/outputs/test
  text: "这是一段测试语音，用于测试语音克隆系统。"
  url: http://localhost:5000
