data:
  output_dir: E:\Pycharm2024\Code_Item\voice_clone_fbm\model\outputs
  temp_dir: E:\Pycharm2024\Code_Item\voice_clone_fbm\model\Temp
  upload_dir: E:\Pycharm2024\Code_Item\voice_clone_fbm\model\uploads
model:
  # 通用配置
  device: cpu
  n_mels: 80
  sample_rate: 22050
  model_dir: E:\Pycharm2024\Code_Item\voice_clone_fbm\model\vocoder\models
  
  # 文本编码器配置
  vocab_size: 256
  text_embed_dim: 512
  encoder_hidden_dim: 1024
  encoder_layers: 4
  encoder_heads: 8
  encoder_dropout: 0.1
  
  # 说话人编码器配置
  audio_n_mels: 80
  speaker_hidden_dim: 256
  speaker_embedding_dim: 256
  speaker_encoder_layers: 3
  embedding_dim: 256
  hidden_dim: 512
  
  # 梅尔解码器配置
  decoder_dim: 512
  decoder_layers: 4
  decoder_heads: 8
  decoder_ff_dim: 2048
  decoder_dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.0001
  max_epochs: 1000
  warmup_steps: 4000
  save_interval: 10
  eval_interval: 5

paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  data_dir: data
server:
  debug: false
  host: 0.0.0.0
  port: 7860
  upload_dir: E:\Pycharm2024\Code_Item\voice_clone_fbm\model\uploads
test:
  audio: E:\Pycharm2024\Code_Item\voice_clone_fbm\model\tests\sample.wav
  output_dir: E:\Pycharm2024\Code_Item\voice_clone_fbm\model\outputs\test
  text: "E:\\Pycharm2024\\Code_Item\\voice_clone_fbm\\model\\\u8FD9\u662F\u4E00\u6BB5\
    \u6D4B\u8BD5\u8BED\u97F3\uFF0C\u7528\u4E8E\u6D4B\u8BD5\u8BED\u97F3\u514B\u9686\
    \u7CFB\u7EDF\u3002"
  url: http://localhost:5000
